import { readFileSync, readdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import matter from 'gray-matter';
import type { Plugin } from 'vite';
import { topicFrontmatterSchema, isPublished, type TopicMeta } from './schema';

const VIRTUAL_ID = 'virtual:bosco/content';
const RESOLVED_ID = '\0' + VIRTUAL_ID;
const CONTENT_ROOT = 'src/content';

/**
 * Build-time content loader + doctrine gate.
 *
 * Reads every `src/content/<category>/<slug>/index.md`, validates its frontmatter against the
 * Zod schema (an invalid topic fails the build), and emits a virtual module `virtual:bosco/content`
 * exporting the published topics with lazy per-tier loaders.
 *
 * The gate is applied HERE, at build time: in a production build, non-`approved` topics are never
 * written into the virtual module, so their metadata and their tier bodies never enter the bundle.
 * Pending doctrine is excluded from production output entirely — not merely hidden at runtime.
 *
 * Preview (dev server, or `CONTENT_PREVIEW=1` build) includes everything so authors can review.
 */
export function boscoContent(): Plugin {
	let root = process.cwd();
	let preview = false;

	return {
		name: 'bosco-content',

		configResolved(config) {
			root = config.root;
			// Preview (include non-approved) in dev, tests, and explicit preview builds.
			// Production builds gate to approved-only.
			preview =
				config.command === 'serve' ||
				process.env.CONTENT_PREVIEW === '1' ||
				Boolean(process.env.VITEST);
		},

		resolveId(id) {
			if (id === VIRTUAL_ID) return RESOLVED_ID;
		},

		load(id) {
			if (id === RESOLVED_ID) return generateModule(root, preview);
		},

		handleHotUpdate({ file, server }) {
			if (file.replace(/\\/g, '/').includes('/src/content/')) {
				const mod = server.moduleGraph.getModuleById(RESOLVED_ID);
				if (mod) server.moduleGraph.invalidateModule(mod);
				server.ws.send({ type: 'full-reload' });
				return [];
			}
		}
	};
}

function generateModule(root: string, preview: boolean): string {
	const contentDir = join(root, CONTENT_ROOT);
	if (!existsSync(contentDir)) return 'export const topics = [];\n';

	const published: Array<{ meta: TopicMeta; category: string; slug: string; tiers: number[] }> = [];

	for (const cat of readdirSync(contentDir, { withFileTypes: true })) {
		if (!cat.isDirectory()) continue;
		const catDir = join(contentDir, cat.name);

		for (const topic of readdirSync(catDir, { withFileTypes: true })) {
			if (!topic.isDirectory()) continue;
			const topicDir = join(catDir, topic.name);
			const indexPath = join(topicDir, 'index.md');
			if (!existsSync(indexPath)) continue;

			const where = `${cat.name}/${topic.name}/index.md`;
			const { data } = matter(readFileSync(indexPath, 'utf8'));
			const parsed = topicFrontmatterSchema.safeParse(data);
			if (!parsed.success) {
				throw new Error(`Invalid content frontmatter in ${where}:\n${parsed.error.message}`);
			}
			const fm = parsed.data;

			if (fm.category !== cat.name) {
				throw new Error(
					`Category "${fm.category}" does not match folder "${cat.name}" in ${where}`
				);
			}
			if (!isPublished(fm.review_status, { preview })) continue;

			for (const t of fm.tiers) {
				if (!existsSync(join(topicDir, `tier-${t}.md`))) {
					throw new Error(`Missing tier-${t}.md for ${cat.name}/${topic.name} (declared in tiers)`);
				}
			}

			published.push({
				meta: { ...fm, slug: topic.name, path: `${cat.name}/${topic.name}` },
				category: cat.name,
				slug: topic.name,
				tiers: fm.tiers
			});
		}
	}

	published.sort((a, b) => a.meta.path.localeCompare(b.meta.path));

	const entries = published.map(({ meta, category, slug, tiers }) => {
		const loaders = tiers
			.map(
				(t) =>
					`${t}: () => import(${JSON.stringify(`/src/content/${category}/${slug}/tier-${t}.md`)})`
			)
			.join(', ');
		return `\t{ ...${JSON.stringify(meta)}, loaders: { ${loaders} } }`;
	});

	return `// Generated by the bosco-content plugin. Do not edit.\nexport const topics = [\n${entries.join(',\n')}\n];\n`;
}
